//This is automated geneerated file!! 

public class Loan_Account__c	 extends SalesForceObject {
	//
	//this is body of class
	//

	// Archive
	boolean Archived__c;

	// Master Archive Object
	boolean Master_Archive_Object__c;

	// Summary
	boolean Summary__c;

	// Summary Record Id
	String Summary_Record_Id__c;

	// ACH Account Number
	String ACH_Account_Number__c;



	// ACH Bank Name
	String ACH_Bank_Name__c;



	// ACH Debit Amount
	double ACH_Debit_Amount__c;

	// ACH Drawer Name
	String ACH_Drawer_Name__c;

	// ACH End Date
	Date ACH_End_Date__c;

	// ACH Frequency Cycle
	double ACH_Frequency_Cycle__c;



	// ACH Next Debit Date
	Date ACH_Next_Debit_Date__c;

	// ACH
	boolean ACH_On__c;



	// ACH Routing Number
	String ACH_Routing_Number__c;

	// ACH Second Debit Date
	Date ACH_Second_Debit_Date__c;

	// ACH Start Date
	Date ACH_Start_Date__c;







	// Accrual Start Date
	Date Accrual_Start_Date__c;

	// Accrual Start Days
	double Accrual_Start_Days__c;

	// Accrual Stop Indicator
	boolean Accrual_Stop_Indicator__c;

	// Accrue Past Maturity
	boolean Accrue_Past_Maturity__c;

	// ACH Debit Day
	double Ach_Debit_Day__c;

	// Active Investor
	boolean Active_Investor__c;

	// Actual Interest Only Payments
	boolean Actual_Interest_Only_Payments__c;

	// Additional Loan Amount
	double Additional_Loan_Amount__c;

	// Aging
	String Aging__c;

	// Allow Interest Split before Maturity
	boolean Allow_Interest_Split_before_Maturity__c;

	// Amortization Schedule Generated
	boolean Amortization_Schedule_Generated__c;

	// Amortization Term
	double Amortization_Term__c;

	// Amount to Current
	double Amount_to_Current__c;

	// Application Date
	Date Application_Date__c;

	// Approval Date
	Date Approval_Date__c;

	// Auto Create Excess Transaction
	boolean Auto_Create_Excess_Transaction__c;

	// Auto Renewable
	boolean Auto_Renewable__c;

	// Available Amount For Next Funding
	double Available_Amount_For_Next_Funding__c;



	// Balloon Payment
	double Balloon_Payment__c;

	// Boarding Date
	Date Boarding_Date__c;





	// Buyback Date
	Date Buyback_Date__c;



	// Cancellation Tolerance Amount
	double Cancellation_Tolerance_Amount__c;



	// Fees Capitalized
	double Capitalized_Fee__c;

	// Interest Capitalized
	double Capitalized_Interest__c;

	// Change Recurring ACH Terms
	boolean Change_Recurring_ACH_Terms__c;

	// Charged Off Capitalized Fees
	double Charged_Off_Capitalized_Fees__c;

	// Charged Off Capitalized Interest
	double Charged_Off_Capitalized_Interest__c;

	// Charged Off Date
	Date Charged_Off_Date__c;

	// Charged Off Fees
	double Charged_Off_Fees__c;

	// Charged Off Interest
	double Charged_Off_Interest__c;

	// Charged Off Principal
	double Charged_Off_Principal__c;





	// Paid Off Date
	Date Closed_Date__c;











	// Due Day
	double Contractual_Due_Day__c;



	// Interest Rate
	double Contractual_Interest_Rate__c;

	// Current Credit Limit
	double Credit_Limit_Current__c;

	// Credit Limit
	double Credit_Limit__c;

	// Current Draw Term
	double Current_Draw_Term__c;



	// Current Loan
	boolean Current_Loan__c;



	// Delinquency Grace Days
	double Delinquency_Grace_Days__c;

	// Delinquent Amount
	double Delinquent_Amount__c;

	// Financed Amount
	double Disbursal_Amount__c;

	// Disbursal By Bank Date
	Date Disbursal_By_Bank_Date__c;

	// Contract Date
	Date Disbursal_Date__c;



	// Amount Funded
	double Disbursed_Amount__c;





	// Discounting Based Payoff
	boolean Discounting_Based_Payoff__c;





	// Draw Period End Date
	Date Draw_Period_End_Date__c;





	// Current Due Day
	double Due_Day__c;

	// Early Pre Payment Penalty Indicator
	boolean Early_Pre_Payment_Penalty_Indicator__c;

	// Eligible For Payoff
	boolean Eligible_For_Payoff__c;



	// Excess
	double Excess__c;

	// Expected Disbursal Date
	Date Expected_Disbursal_Date__c;

	// Payment Start Date
	Date Expected_Repayment_Start_Date__c;

	// Fee Accrued
	double Fee_Accrued__c;



	// Fees Paid
	double Fees_Paid__c;

	// Fees Remaining
	double Fees_Remaining__c;

	// Fees Suspended
	double Fees_Suspended__c;

	// First Payment Date
	Date First_Installment_Date__c;











	// Funding in Tranches
	boolean Funding_in_Tranches__c;

	// Late Charge Grace Days
	double Grace_Period_for_Repayments__c;





	// Include In Buyback Process
	boolean Include_In_Buyback_Process__c;

	// Include In Credit Reporting
	boolean Include_In_Metro2_File__c;

	// Income Suspended
	double Income_Suspended__c;



	// Interest Accrued
	double Interest_Accrued_Not_Due__c;

	// Interest Accrued On Investment Loans
	double Interest_Accrued_On_Investment_Loans__c;



	// Interest Donated
	double Interest_Donated__c;

	// Interest Donated on Rollover
	double Interest_Donated_on_Rollover__c;

	// Interest On Overdue Paid
	double Interest_On_Overdue_Paid__c;

	// Interest On Overdue Suspended
	double Interest_On_Overdue_Suspended__c;

	// Interest On Total Overdue
	double Interest_On_Total_Overdue__c;

	// Interest Only Payment Amt
	double Interest_Only_Payment_Amt__c;

	// Interest Only Period
	double Interest_Only_Period__c;

	// Interest Paid
	double Interest_Paid__c;

	// Interest Payback
	double Interest_Payback__c;

	// Interest Payback on Rollover
	double Interest_Payback_on_Rollover__c;

	// Interest Posted
	double Interest_Posted__c;

	// Interest Posting Day
	double Interest_Posting_Day__c;



	// Last Interest Rate
	double Interest_Rate_Last__c;

	// Interest Rate Past Maturity
	double Interest_Rate_Past_Maturity__c;



	// Interest Rate on Due IOA
	double Interest_Rate_on_Due_IOA__c;

	// Interest Rate on Due Interest
	double Interest_Rate_on_Due_Interest__c;

	// Interest Rate on Due Principal
	double Interest_Rate_on_Due_Principal__c;

	// Interest Remaining
	double Interest_Remaining__c;

	// Interest Service Fee
	double Interest_Service_Fee__c;

	// Interest Suspended
	double Interest_Suspended__c;



	// Interest Waived
	double Interest_Waived__c;

	// Estimated Interest
	double Interest_estimated__c;

	// Invalid Data
	boolean Invalid_Data__c;



	// Investment Product loan
	boolean Investment_Product_loan__c;

	// Is Capitalization Enabled
	boolean Is_Capitalization_Enabled__c;

	// Is Eligible For Write Off
	boolean Is_Eligible_For_Write_Off__c;

	// Is Interest Posting
	boolean Is_Interest_Posting_Enabled__c;

	// Rescheduled
	boolean Is_Rescheduled__c;



	// Enabled
	boolean LA_Amortization_Enabled__c;





	// Last Accrual Date
	Date Last_Accrual_Date__c;

	// Last Advance Date
	Date Last_Advance_Date__c;

	// Last Bank Transaction Date
	Date Last_Bank_Transaction_Date__c;

	// Last Billed Amount
	double Last_Billed_Amount__c;

	// Last Disbursal Transaction Amount
	double Last_Disbursal_Amount__c;

	// Last Disbursal Transaction Date
	Date Last_Disbursal_Date__c;

	// Maturity Date
	Date Last_Installment_Date__c;

	// Last Interest Posting Date
	Date Last_Interest_Posting_Date__c;

	// Last Investment Loan Payment Changed
	boolean Last_Investment_Loan_Payment_Changed__c;

	// Last Payment Amount
	double Last_Payment_Amount__c;

	// Last Payment Date
	Date Last_Payment_Date__c;

	// Last Transaction Id
	String Last_Transaction_Id__c;

	// Last Transaction Timestamp
	Date Last_Transaction_Timestamp__c;



	// LoanCnt
	double LoanCnt__c;

	// Loan Account External Id
	String Loan_Account_External_Id__c;

	// Loan Amount
	double Loan_Amount__c;

	// Loan Balance
	double Loan_Balance__c;

	// Loan Cycle Count
	double Loan_Cycle_Count__c;

	// Effective Date
	Date Loan_Effective_Date__c;







	// Long Term Loan
	boolean Long_Term_Loan__c;







	// MCA Transaction Category
	String MCA_Transaction_Category__c;



	// Market Place Value
	double Market_Place_Value__c;

	// Current Maturity Date
	Date Maturity_Date_Current__c;

	// Maximum Advance Amount
	double Maximum_Advance_Amount__c;

	// Maximum Draw Amount
	double Maximum_Draw_Amount__c;

	// Account Status Code
	String Metro2_Account_Status_Code__c;



	// Highest Bal Amount
	double Metro2_Account_highest_bal_amount__c;

	// Last Reported Metro2 Date
	Date Metro2_Account_pmt_history_date__c;

	// CCCD Date
	Date Metro2_CCCD_Date__c;

	// CIIC Date
	Date Metro2_CIIC_Date__c;

	// Compliance Conditon Code
	String Metro2_Compliance_Condition_Code__c;

	// Consumer Information Code
	String Metro2_Consumer_Information_Code__c;

	// Date of First Delinquency
	Date Metro2_First_Delinquency_Date__c;

	// Payment History
	String Metro2_Payment_History__c;

	// Payment Rating
	String Metro2_Payment_Rating__c;



	// Metro2 Special Comment
	String Metro2_Special_Comment__c;

	// Migration Date
	Date Migration_Date__c;

	// Minimum Advance Amount
	double Minimum_Advance_Amount__c;



	// Minimum Amount Due
	double Minimum_Amount_Due__c;

	// Minimum Draw Amount
	double Minimum_Draw_Amount__c;

	// Minimum Bill Amount
	double Minimum_Due_Amount_On_Billing__c;

	// New Field 3
	String New_Field_3__c;

	// Next Capitalization Date
	Date Next_Capitalization_Date__c;

	// Next Commission Payment Date
	Date Next_Commission_Payment_Date__c;

	// Next Credit Bureau Payment Profile Date
	Date Next_Crb_Payment_Profile_Date__c;

	// Next Due Generation Date
	Date Next_Due_Generation_Date__c;

	// Next Due Date
	Date Next_Installment_Date__c;

	// Next Interest Posting Date
	Date Next_Interest_Posting_Date__c;

	// Next Repayment Amount As Of Today
	double Next_Repayment_Amount_As_Of_Today__c;

	// Days Past Due
	double Number_of_Days_Overdue__c;

	// Term
	double Number_of_Installments__c;







	// OT ACH Account Number
	String OT_ACH_Account_Number__c;



	// OT ACH Bank Name
	String OT_ACH_Bank_Name__c;

	// OT ACH Debit Date
	Date OT_ACH_Debit_Date__c;

	// OT ACH Drawer Address Line 1
	String OT_ACH_Drawer_Address1__c;

	// OT ACH Drawer Address Line 2
	String OT_ACH_Drawer_Address2__c;

	// OT ACH Drawer City
	String OT_ACH_Drawer_City__c;

	// OT ACH Drawer Name
	String OT_ACH_Drawer_Name__c;

	// OT ACH Drawer State
	String OT_ACH_Drawer_State__c;

	// OT ACH Drawer Zip
	String OT_ACH_Drawer_Zip__c;

	// OT ACH Fee Amount
	double OT_ACH_Fee_Amount__c;

	// OT ACH Payment Amount
	double OT_ACH_Payment_Amount__c;



	// OT ACH Routing Number
	String OT_ACH_Routing_Number__c;



	// Oldest Unpaid  Due Date
	Date Oldest_Due_Date__c;

	// Origin
	String Origin_Source__c;

	// Originating Bank Fee Share
	double Originating_Bank_Fee_Share__c;

	// Outstanding>Writeoff
	String OutstandingGreaterThanWriteoff__c;

	// Overdue Amount As Of Today
	double Overdue_Amount_As_Of_Today__c;

	// Overdue Interest Rate
	double Overdue_Interest_Rate__c;

	// Overdue Interest
	double Overdue_Interest__c;

	// Overdue Penalty
	double Overdue_Penalty__c;

	// Overdue Principal
	double Overdue_Principal__c;

	// Parent Loan Of Investment
	String Parent_Loan_Of_Investment__c;

	// Today's Payoff
	double Pay_Off_Amount_As_Of_Today__c;

	// Payment Amount
	double Payment_Amount__c;



	// Payment Frequency Cycle
	double Payment_Frequency_Cycle__c;



	// Payment Tolerance End Date
	Date Payment_Tolerance_End_Date__c;

	// Payment Tolerance Rate
	double Payment_Tolerance_Rate__c;

	// Payment Tolerance Start Date
	Date Payment_Tolerance_Start_Date__c;

	// Payoff Fee
	boolean Payoff_Fee_Indicator__c;

	// Penalty Paid
	double Penalty_Paid__c;

	// Penalty Remaining
	double Penalty_Remaining__c;

	// Periodic Charge Start Date
	Date Periodic_Charge_Start_Date__c;

	// Periodic Fee
	boolean Periodic_Fee__c;

	// Current Payment Amount
	double Pmt_Amt_Cur__c;

	// Pre Bill Days
	double Pre_Bill_Days__c;

	// Pre Paid Interest
	double Pre_Paid_Interest_Amount__c;

	// Pre Paid Interest Paid Till Date
	Date Pre_Paid_Interest_Paid_Till_Date__c;



	// Prepayment Penalty Indicator
	boolean Prepayment_Penalty_Indicator__c;

	// Prepayment Penalty Periods
	double Prepayment_Penalty_Periods__c;

	// Prepayment Penalty Value
	double Prepayment_Value__c;

	// Last Due Date
	Date Previous_Installment_Date__c;

	// Prin Int EMI Generated On Total
	boolean Prin_Int_EMI_Generated_On_Total__c;

	// Principal Adjustment - Sub
	double Principal_Adjustment_Subtract__c;

	// Principal Adjustment - Add
	double Principal_Adjustment__c;

	// Principal Donated on Rollover
	double Principal_Donated_on_Rollover__c;

	// Principal Interest EMI Generated On Req
	boolean Principal_Interest_EMI_Generated_On_Req__c;

	// Principal/Advance Paid
	double Principal_Paid__c;

	// Principal Payback On Rollover
	double Principal_Payback_On_Rollover__c;

	// Principal/Advance Posted
	double Principal_Posted__c;

	// Principal Reinvested On Rollover
	double Principal_Reinvested_On_Rollover__c;

	// Principal/Advance Remaining
	double Principal_Remaining__c;



	// Protect Borrower Rebate
	double Protect_Borrower_Rebate__c;

	// Protect Enabled
	boolean Protect_Enabled__c;

	// Protect Fee Percent
	double Protect_Fee_Percent__c;

	// Protect Split Charged To Investor
	double Protect_Split_Charged_To_Investor__c;





	// Protect Fee Amount
	double Protect_fee_amount__c;

	// Last Rate Change Date
	Date Rate_Change_Dt_Last__c;

	// Next Rate Change Date
	Date Rate_Change_Dt_Next__c;

	// Recalculate Interest
	boolean Recalculate_Interest_Flag__c;

	// Recovered Principal Balance
	double Recovered_Principal_Balance__c;

	// Refinanced
	boolean Refinanced__c;

	// Reinvest Interest In Same Loan
	boolean Reinvest_Interest_In_Same_Loan__c;

	// Reinvest Interest
	double Reinvest_Interest__c;

	// Reinvest Interest on Rollover
	double Reinvest_Interest_on_Rollover__c;

	// Remaining Amount for Funding
	double Remaining_Loan_Amount__c;













	// Is Repayment Tied to Meeting Schedule
	boolean Repayment_Tied_to_Meeting_Schedule__c;



	// Reserve Amount for Next Due
	double Reserve_Amount_for_Next_Due__c;

	// Rollover Applicable
	boolean Rollover_Applicable__c;





	// Second Payment Date
	Date Second_Installment_Date__c;



	// Status Order
	double Status_Order__c;

	// Is Suspended
	boolean Suspended__c;

	// Current Term
	double Term_Cur__c;

	// Total Term
	double Term_Total__c;



	// Total Amount Overdue
	double Total_Amount_Overdue__c;

	// Total Amount Paid
	double Total_Amount_Paid__c;

	// Total Amount Remaining
	double Total_Amount_Remaining__c;

	// Total Due Charges
	double Total_Due_Charges__c;







	// Total Refinance Amount (Actual)
	double Total_Refinance_Amount_Actual__c;

	// Total Refinance Amount (Expected)
	double Total_Refinance_Amount_Expected__c;

	// Uncleared Disbursal Amount
	double Uncleared_Disbursal_Amount__c;

	// Uncleared Payment Amount
	double Uncleared_Repayment_Amount__c;

	// Uncleared Written Off Amount
	double Uncleared_Written_Off_Amount__c;

	// Unpaid Bills
	boolean Unpaid_Bills__c;

	// Payoff Tolerance Amount
	double Write_off_Tolerance_Amount__c;

	// Draw Term
	double draw_term__c;

	// Delinquent
	boolean la_delinquency_flag__c;

	// Matured
	boolean la_matured_flag__c;

	// Next Amortization Date
	Date la_next_amortization_date__c;

}